---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
- name: pcf-tile-automation

params:
  PRODUCT_NAME:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  ERRANDS_TO_DISABLE:

run:
  path: pcf-tile-automation/tasks/disable-errands/task.sh
