---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_DECRYPTION_PWD:

inputs:
  - name: pcf-tile-automation

run:
  path: pcf-tile-automation/tasks/config-opsman/task.sh
