resources:
- name: pcf-tile-automation
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-tile-automation.git
    branch: master
    private_key: {{git_private_key}}
    paths: [ci/Dockerfile]

- name: pcf-tile-automation-image
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: latest
    username: czero
    password: {{czero_dockerhub_password}}

- name: pcf-tile-automation-image-rc
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: release-candidate
    username: czero
    password: {{czero_dockerhub_password}}

- name: cflinuxfs2
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
    tag: latest

- name: om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{images_pipeline_github_token}}

- name: yaml-patch
  type: github-release
  source:
    user: krishicks
    repository: yaml-patch
    access_token: {{images_pipeline_github_token}}

- name: cf-cli-tarball
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: releases/v([\d\.]+)/cf-cli_.*_linux_x86-64.tgz
    region_name: us-west-1

- name: cliaas
  type: github-release
  source:
    user: pivotal-cf
    repository: cliaas
    access_token: {{images_pipeline_github_token}}

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{images_pipeline_github_token}}

- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: {{images_pipeline_github_token}}

- name: om-beta
  type: github-release
  source:
    user: c0-ops
    repository: om
    access_token: {{images_pipeline_github_token}}

- name: stemcell-downloader
  type: github-release
  source:
    user: pivotal-cf
    repository: pcf-product-stemcell-downloader
    access_token: {{images_pipeline_github_token}}

- name: steamroll
  type: github-release
  source:
    user: krishicks
    repository: concourse-pipeline-steamroller
    access_token: {{images_pipeline_github_token}}

jobs:
- name: build-pcf-tile-automation-image
  serial_groups: [pcf-tile-automation-image]
  plan:
  - aggregate:
    - get: pcf-tile-automation
      trigger: true
    - get: cflinuxfs2
      trigger: true
      params: {save: true}
    - get: yaml-patch 
      params: {globs: ["*linux*"]}
    - get: om
      params: {globs: ["*linux*"]}
    - get: cf-cli-tarball
    - get: cliaas
      params: {globs: ["*linux*"]}
    - get: pivnet-cli
      params: {globs: ["*linux*"]}
    - get: govc
      params: {globs: ["*linux_amd64*"]}
    - get: om-beta
      params: {globs: ["*linux*"]}
      version: { tag: '0.17-beta.0' }
    - get: stemcell-downloader
      params: {globs: ["*linux*"]}
    - get: steamroll
      params: {globs: ["*linux*"]}

  - task: prepare-workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: czero/cflinuxfs2}
      inputs:
      - name: pcf-tile-automation
      - name: om
      - name: yaml-patch 
      - name: cf-cli-tarball
      - name: cliaas
      - name: pivnet-cli
      - name: govc
      - name: om-beta
      - name: stemcell-downloader
      - name: steamroll
      outputs:
      - name: workspace
      run:
        path: bash
        args:
        - -c
        - |
          cp pcf-tile-automation/ci/Dockerfile workspace

          cp om/om-linux workspace
          chmod +x workspace/om-linux

          cp yaml-patch/yaml_patch_linux workspace
          chmod +x workspace/yaml_patch_linux

          tar -C workspace -xf cf-cli-tarball/*.tgz cf
          chmod +x workspace/cf

          cp cliaas/cliaas-linux workspace
          chmod +x workspace/cliaas-linux

          cp pivnet-cli/pivnet-linux-* workspace/pivnet-cli
          chmod +x workspace/pivnet-cli

          gunzip govc/govc_linux_amd64.gz
          cp govc/govc_linux_amd64 workspace/govc
          chmod +x workspace/govc

          cp om-beta/om-linux workspace/om-linux-beta
          chmod +x workspace/om-linux-beta

          cp stemcell-downloader/stemcell-downloader-linux workspace/stemcell-downloader
          chmod +x workspace/stemcell-downloader

          cp steamroll/steamroll_linux workspace/steamroll
          chmod +x workspace/steamroll

  - put: pcf-tile-automation-image-rc
    params:
      load_base: cflinuxfs2
      build: workspace

- name: test-pcf-tile-automation-image
  serial_groups: [pcf-tile-automation-image]
  plan:
  - get: pcf-tile-automation-image-rc
    trigger: true
    passed: [build-pcf-tile-automation-image]
    params:
      skip_download: true
  - task: test-for-required-binaries
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
          tag: release-candidate
      run:
        path: sh
        args:
        - -c
        - |
          set -e
          which om-linux
          which yaml_patch_linux
          which cf
          which cliaas-linux
          which pivnet-cli
          which govc
          which om-linux-beta
          which stemcell-downloader
          which jq
          which terraform
          which gcloud
          which gem
          which pip
          which uaac
          which aws
          which openstack
          which neutron
          which steamroll

- name: promote-image
  serial_groups: [pcf-tile-automation-image]
  plan:
  - get: pcf-tile-automation-image-rc
    passed: [test-pcf-tile-automation-image]
    trigger: true
    params:
      save: true
  - put: pcf-tile-automation-image
    params:
      load: pcf-tile-automation-image-rc
      tag_as_latest: true
