---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-tile-automation
- name: version
- name: fly

outputs:
- name: pcf-tile-automation-release-tarball
- name: pivnet-metadata

params:
  AVAILABILITY: Admins Only

run:
  path: bash
  args:
  - -c
  - |
    set -o pipefail
    set -eu

    chmod +x fly/fly
    export PATH="$PWD/fly":$PATH

    root=$PWD

    echo "Creating upgrade-ert pipeline from upgrade-tile pipeline"
    pushd pcf-tile-automation
      mkdir -p upgrade-ert

      sed \
        -e 's/^product_slug:/# product_slug:/' \
        -e 's/^product_name:/# product_name:/' \
        upgrade-tile/params.yml > upgrade-ert/params.yml

      cat ci/yaml_license_header <(
        cat upgrade-tile/pipeline.yml | yaml_patch_linux -o operations/create-upgrade-ert-pipeline.yml
      ) > upgrade-ert/pipeline.yml
    popd

    # Switch pcf-tile-automation to point at Pivnet release of pcf-tile-automation instead
    # of GitHub
    version=v$(cat version/version)

    set +e # read -d '' requires this
    read -r -d '' hardcode_pivnet_version <<EOF
    - op: replace
      path: /resources/name=pcf-tile-automation-tarball/source/product_version
      value: $version
    EOF

    read -r -d '' test_for_pcf_pipelines_git <<EOF
    - op: test
      path: /resources/name=pcf-tile-automation
      value:
        name: pcf-tile-automation
        type: git
        source:
          uri: git@github.com:pivotal-cf/pcf-tile-automation.git
          branch: master
          private_key: "{{git_private_key}}"
    EOF
    set -e

    files=$(
      find pcf-tile-automation \
      -type f \
      -name pipeline.yml |
      grep -v pcf-tile-automation/ci
    )

    for f in ${files[@]}; do
      if [[ $(cat $f | yaml_patch_linux -o <(echo "$test_for_pcf_pipelines_git") 2>/dev/null ) ]]; then
        echo "Using pivnet release for ${f}"
        cat $f |
        yaml_patch_linux \
          -o pcf-tile-automation/operations/use-pivnet-release.yml \
          -o <(echo "$hardcode_pivnet_version") \
          > $f.bk
        mv $f.bk $f

        fly fmt --write --config $f

        # Remove git_private_key from params as it is no longer needed
        params_file=$(dirname $f)/params.yml
        sed -i -e '/git_private_key:/d' $params_file
      fi
    done

    echo "Creating install-pcf/vsphere/offline/pipeline.yml"
    mkdir -p pcf-tile-automation/install-pcf/vsphere/offline
    cat > steamroll_config.yml <<EOF
    resource_map:
      "pcf-tile-automation": $root/pcf-tile-automation
    EOF
    steamroll -p pcf-tile-automation/install-pcf/vsphere/pipeline.yml -c steamroll_config.yml |
    yaml_patch_linux \
      -o pcf-tile-automation/operations/create-install-pcf-vsphere-offline-pipeline.yml \
      > vsphere-offline.yml
    fly fmt -c vsphere-offline.yml > pcf-tile-automation/install-pcf/vsphere/offline/pipeline.yml

    echo "Creating install-pcf/vsphere/offline/params.yml"
    cp pcf-tile-automation/install-pcf/vsphere{,/offline}/params.yml
    sed -i \
      -e '/pivnet_token:/d' \
      -e '/ert_major_minor_version:/d' \
      -e '/opsman_major_minor_version:/d' \
      -e '/company_proxy_domain:/d' \
      pcf-tile-automation/install-pcf/vsphere/offline/params.yml
    cat >> pcf-tile-automation/install-pcf/vsphere/offline/params.yml <<EOF

    # offline resource config
    s3_endpoint:
    s3_bucket:
    s3_access_key_id:
    s3_secret_access_key:
    EOF

    echo "Creating release metadata.yml"
    release_date=$(date +%Y-%m-%d)
    cat >> pivnet-metadata/metadata.yml <<EOF
    ---
    release:
      version: "${version}"
      release_date: "${release_date}"
      release_notes_url: "https://github.com/pivotal-cf/pcf-tile-automation/releases"
      description: |
        Concourse Pipeline Templates and Scripts for PCF Platform Ops Automation
      availability: $AVAILABILITY
      release_type: Beta Release
      eula_slug: "pivotal_beta_eula"
      eccn: "5D002"
      license_exception: "TSU"
      user_group_ids:
      - 6   # Pivotal Internal Early Access
      - 159 # C[0] PCF Automation Pipelines Access
      - 64  #| Pivotal SI Partners Known and Potential Partners. 
    EOF

    exclusions="--exclude .git* --exclude ci --exclude *.go --exclude run_bash_testsuite.sh"
    if [[ "$AVAILABILITY" != "Admins Only" ]]; then
      exclusions+=" --exclude download-offline-resources"
      exclusions+=" --exclude install-pcf/vsphere/offline"
      exclusions+=" --exclude create-offline-pinned-pipelines"
      exclusions+=" --exclude unpack-pcf-tile-automation-combined"
    fi

    echo "Creating release tarball, ommitting the following globs:"
    echo "${exclusions}"
    tar \
      $exclusions \
      --create \
      --gzip \
      --file pcf-tile-automation-release-tarball/pcf-tile-automation-$version.tgz \
      pcf-tile-automation
