---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-tile-automation 
- name: pivnet-opsmgr

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: pcf-tile-automation/install-pcf/gcp/tasks/upload-opsman/task.sh
