---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  PRODUCT_NAME:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  OTHER_AZS:
  NETWORK_NAME:
  PLAN_NAME:
  PLAN_DESCRIPTION:
  PLAN_MAX_STORAGE_MB:
  PLAN_MAX_USER_CONNECTIONS:
  PLAN_INVISIBLE:
  PROTECTION_EMAIL:
  BACKUP_CRON_SCHEDULE:
  BACKUP_SCP_HOST:
  BACKUP_SCP_PORT:
  BACKUP_SCP_USER:
  BACKUP_SCP_KEY:
  BACKUP_SCP_DESTINATION:
  SYSLOG_HOST:
  SYSLOG_PORT:
  MYSQL_SERVER_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MONITORING_INSTANCES:
  MYSQL_BROKER_INSTANCES:
inputs:
  - name: pcf-tile-automation
  - name: tool-om

run:
  path: pcf-tile-automation/tasks/config-mysql/task.sh
