---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  SERVICE_NETWORK:
  SYSLOG_SELECTOR:
  SYSLOG_HOST:
  SYSLOG_PORT:
  DISABLE_TLS:  
  SMALL_PLAN_STATUS:
  MEDIUM_PLAN_STATUS:
  LARGE_PLAN_STATUS:
  BACKUPS_SELECTOR:
  S3_ACCESS_KEY: {{backups_selector.s3.access_key_id}}
  S3_SECRET_KEY: {{backups_selector.s3.secret_access_key}}
  S3_ENDPOINT: {{backups_selector.s3.endpoint_url}}
  S3_SIGNATURE: {{backups_selector.s3.signature_version}}
  S3_BUCKET: {{backups_selector.s3.bucket_name}}
  S3_PATH: {{backups_selector.s3.path}}
  S3_SCHEDULE: {{backups_selector.s3.cron_schedule}}

inputs:
  - name: pcf-tile-automation
  - name: tool-om

run:
  path: pcf-tile-automation/tasks/config-redis/task.sh
