resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
        #- name: govc
        #  type: github-release
        #  source:
        #    user: vmware
        #    repository: govmomi
        #    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pcf-tile-automations
  type: git
  source:
#   uri: https://github.com/pivotal-cf/pcf-tile-automations
#   branch: master
    uri: https://github.com/bhudlemeyer/pcf-tile-automation.git
    branch: master
    username: {{github_token}}

jobs:
- name: config-ops-metrics-tile
  plan:
  - aggregate:
    - get: pcf-tile-automations
      trigger: true
    - get: tool-om
      params: {globs: ["*linux*"]}

  - task: config-metrics-tile
    file: pcf-tile-automations/tasks/config-ops-metrics/task.yml
    params:
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_HOST: {{opsman_uri}}
      SINGLETON_JOB_AZ: {{az_1_name}}
      OTHER_JOB_AZS: {{infra_nw_azs}}
      NETWORK_NAME: {{infra_network_name}}
      JMX_ADMIN_USR: {{jmx_admin_usr}}
      JMX_ADMIN_PWD: {{jmx_admin_pwd}}
      JMX_SECURITY_LOGGING: {{jmx_security_logging}}
      JMX_USE_SSL: {{jmx_use_ssl}}
