resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
        #- name: govc
        #  type: github-release
        #  source:
        #    user: vmware
        #    repository: govmomi
        #    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pcf-tile-automation
  type: git
  source:
    uri: https://github.com/bhudlemeyer/pcf-tile-automation.git
    branch: master
    username: {{github_token}}

# - name: customer-repo
#   type: git
#   source:
#     uri: https://github.com/rahul-kj/sample-customer-repo
#     branch: master

- name: jmx-bridge
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-metrics
    product_version: {{jmx_major_minor_version}}
    sort_by: semver

jobs:
- name: upload-ops-metrics-tile
  plan:
  - aggregate:
    - get: pcf-tile-automation
      trigger: true
    - get: pivnet-product
      resource: jmx-bridge
    - get: tool-om
    - get: pivnet-cli
      params: {globs: ["*linux-amd64*"]}

  - task: upload-tile
    file: pcf-tile-automation/tasks/upload-product-and-stemcell/task.yml
    attempts: 3
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: {{company_proxy_domain}}
      OM_IP: {{om_ip}}
      IAAS: {{iaas_type}}

  - task: stage-tile
    file: pcf-tile-automation/tasks/stage-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PRODUCT_NAME: p-metrics

- name: config-ops-metrics-tile
  plan:
  - aggregate:
    - get: pcf-tile-automation
      trigger: true
      passed: [upload-ops-metrics-tile]
    - get: tool-om
      params: {globs: ["*linux*"]}
      passed: [upload-ops-metrics-tile]

  - task: config-ops-metrics-tile
    file: pcf-tile-automation/tasks/config-ops-metrics/task.yml
    params:
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_HOST: {{opsman_uri}}
      SINGLETON_JOB_AZ: {{singleton_az}}
      OTHER_JOB_AZS: {{other_job_az}}
      NETWORK_NAME: {{network_name}}
      JMX_ADMIN_USR: {{jmx_admin_usr}}
      JMX_ADMIN_PWD: {{jmx_admin_pwd}}
      JMX_SECURITY_LOGGING: {{jmx_security_logging}}
      JMX_USE_SSL: {{jmx_use_ssl}}


#uncomment below section if you want to automatically deploy once config is completed


#- name: product-apply-changes
#  plan:
#  - aggregate:
#    - get: pcf-tile-automation
#      trigger: true
#      passed: [config-ops-metrics-tile]
#    - get: tool-om
#      params: {globs: ["*linux*"]}
#      passed: [config-ops-metrics-tile]
#
#  - task: apply-changes
#    file: pcf-tile-automation/tasks/apply-changes/task.yml
#    attempts: 3
#    params:
#      OPSMAN_URI: {{opsman_uri}}
#      OPSMAN_USERNAME: {{opsman_admin_username}}
#      OPSMAN_PASSWORD: {{opsman_admin_password}}
#      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
