resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
        #- name: govc
        #  type: github-release
        #  source:
        #    user: vmware
        #    repository: govmomi
        #    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: {{github_token}} ## Optional: Removing this will cause you to hit the rate limit

- name: pcf-tile-automations
  type: git
  source:
    uri: https://github.com/bhudlemeyer/pcf-tile-automation.git
    branch: master
    username: {{github_token}}

# - name: customer-repo
#   type: git
#   source:
#     uri: https://github.com/rahul-kj/sample-customer-repo
#     branch: master

- name: apm-metrics
  type: pivnet
  check_every: {{pivnet_poll_interval}}
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-metrics
    product_version: {{metrics_major_minor_version}}
    sort_by: semver

jobs:
- name: upload-pcf-metrics-tile
  plan:
  - aggregate:
    - get: pcf-tile-automations
      trigger: true
    - get: pivnet-product
      resource: apm-metrics
    - get: tool-om
    - get: pivnet-cli
      params: {globs: ["*linux-amd64*"]}

  - task: upload-tile
    file: pcf-tile-automations/tasks/upload-product-and-stemcell/task.yml
    attempts: 3
    params:
      OPS_MGR_HOST: {{opsman_uri}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: {{company_proxy_domain}}
      OM_IP: {{om_ip}}
      IAAS: {{iaas_type}}

  - task: stage-tile
    file: pcf-tile-automations/tasks/stage-product/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      PRODUCT_NAME: apm


- name: config-pcf-metrics-tile
  plan:
  - aggregate:
    - get: pcf-tile-automations
      trigger: true
      passed: [upload-pcf-metrics-tile]
    - get: tool-om
      params: {globs: ["*linux*"]}
      passed: [upload-pcf-metrics-tile]

  - task: config-metrics-tile
    file: pcf-tile-automations/tasks/config-pcf-metrics/task.yml
    params:
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_HOST: {{opsman_uri}}
      SINGLETON_JOB_AZ: {{az_1_name}}
      OTHER_JOB_AZS: {{infra_nw_azs}}
      NETWORK_NAME: {{infra_network_name}}
      NOTIFICATIONS_EMAIL: {{metrics_notifications_email}}

# uncomment to deploy pcf metrics after config completes. 
# BE ADVISED PCF METRICS REQUIRES REDIS BE INSTALLED TO DEPLOY SUCCESSFULLY.

#- name: product-apply-changes
#  plan:
#  - aggregate:
#    - get: pcf-tile-automations
#      trigger: true
#      passed: [config-metrics-tile]
#    - get: tool-om
#      params: {globs: ["*linux*"]}
#      passed: [config-metrics-tile]
#
#  - task: apply-changes
#    file: pcf-tile-automations/tasks/apply-changes/task.yml
#    attempts: 3
#    params:
#      OPSMAN_URI: {{opsman_uri}}
#      OPSMAN_USERNAME: {{opsman_admin_username}}
#      OPSMAN_PASSWORD: {{opsman_admin_password}}
#      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
