---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPSMAN_URI:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:

inputs:
  - name: pcf-tile-automation
  - name: tool-om

run:
  path: pcf-tile-automation/tasks/config-sso/task.sh
