---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  SERVICE_NETWORK:
  SYSLOG_SELECTOR:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SERVICE_LOG_EXTERNAL_SYSLOG:
  SYSLOG_ENABLE_TLS:  
  SYSLOG_PERMITTED_PEER:
  SYSLOG_SSL_CERT:
  SMOKE_TEST_PLAN:
  DIST_SYSTEM_ID:
  PLAN_1_STATUS:
  PLAN_1_NAME:
  PLAN_1_DESC:
  PLAN_1_METRICS:
  PLAN_1_SERVICE_ACCESS:
  PLAN_1_SERVICE_INSTANCE:
  PLAN_1_SERVERS_PER_CLUSTER:
  PLAN_1_DEFAULT_NUM_SERVERS:
  PLAN_1_AVAILABILITY_ZONES:
  PLAN_1_LOCATOR_VM:
  PLAN_1_PERSIS_DISK_LOCATOR:
  PLAN_1_SERVER_VM:
  PLAN_1_PERSIS_DISK_SERVER: 
  PLAN_2_STATUS:
  PLAN_2_NAME:
  PLAN_2_DESC:
  PLAN_2_METRICS:
  PLAN_2_SERVICE_ACCESS:
  PLAN_2_SERVICE_INSTANCE:
  PLAN_2_SERVERS_PER_CLUSTER:
  PLAN_2_DEFAULT_NUM_SERVERS:
  PLAN_2_AVAILABILITY_ZONES:
  PLAN_2_LOCATOR_VM:
  PLAN_2_PERSIS_DISK_LOCATOR:
  PLAN_2_SERVER_VM:
  PLAN_2_PERSIS_DISK_SERVER:
  PLAN_3_STATUS:
  PLAN_3_NAME:
  PLAN_3_DESC:
  PLAN_3_METRICS:
  PLAN_3_SERVICE_ACCESS:
  PLAN_3_SERVICE_INSTANCE:
  PLAN_3_SERVERS_PER_CLUSTER:
  PLAN_3_DEFAULT_NUM_SERVERS:
  PLAN_3_AVAILABILITY_ZONES:
  PLAN_3_LOCATOR_VM:
  PLAN_3_PERSIS_DISK_LOCATOR:
  PLAN_3_SERVER_VM:
  PLAN_3_PERSIS_DISK_SERVER:
  PLAN_4_STATUS:
  PLAN_4_NAME:
  PLAN_4_DESC:
  PLAN_4_METRICS:
  PLAN_4_SERVICE_ACCESS:
  PLAN_4_SERVICE_INSTANCE:
  PLAN_4_SERVERS_PER_CLUSTER:
  PLAN_4_DEFAULT_NUM_SERVERS:
  PLAN_4_AVAILABILITY_ZONES:
  PLAN_4_LOCATOR_VM:
  PLAN_4_PERSIS_DISK_LOCATOR:
  PLAN_4_SERVER_VM:
  PLAN_4_PERSIS_DISK_SERVER:
  PLAN_5_STATUS:
  PLAN_5_NAME:
  PLAN_5_DESC:
  PLAN_5_METRICS:
  PLAN_5_SERVICE_ACCESS:
  PLAN_5_SERVICE_INSTANCE:
  PLAN_5_SERVERS_PER_CLUSTER:
  PLAN_5_DEFAULT_NUM_SERVERS:
  PLAN_5_AVAILABILITY_ZONES:
  PLAN_5_LOCATOR_VM:
  PLAN_5_PERSIS_DISK_LOCATOR:
  PLAN_5_SERVER_VM:
  PLAN_5_PERSIS_DISK_SERVER:
  DEV_PLAN_STATUS:
  ERRANDS_TO_DISABLE:
  PREDELETE_ERRANDS_TO_DISABLE:

inputs:
  - name: pcf-tile-automation
  - name: tool-om

run:
  path: pcf-tile-automation/tasks/config-pcc/task.sh
